name: 'study-kotlin'

services:
  backend:
    container_name: study-kotlin-backend-container
    hostname: study-kotlin-backend-server
    image: study-kotlin/backend:dev
    build:
      context: .
      dockerfile: ./infra/docker/backend/Dockerfile
      cache_from:
        - study-kotlin/backend:cache
      target: dev
    depends_on:
      - mysql
      - postgres
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL:-jdbc:mysql://mysql:3306/kotlin}
      - MYSQL_DATABASE_USER=${MYSQL_DATABASE_USER:-test}
      - MYSQL_DATABASE_PASSWORD=${MYSQL_DATABASE_PASSWORD:-test}
      - POSTGRES_DATABASE_URL=${POSTGRES_DATABASE_URL:-jdbc:postgresql://postgres:5432/kotlin2}
      - POSTGRES_DATABASE_USER=${POSTGRES_DATABASE_USER:-test}
      - POSTGRES_DATABASE_PASSWORD=${POSTGRES_DATABASE_PASSWORD:-test}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app

  mysql:
    container_name: study-kotlin-mysql-container
    hostname: study-kotlin-mysql-server
    image: study-kotlin/mysql:dev
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
      cache_from:
        - study-kotlin/mysql:cache
    ports:
      - '13316:3306'
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./infra/docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME:-kotlin}
      - MYSQL_USER=${MYSQL_DB_USER:-test}
      - MYSQL_PASSWORD=${MYSQL_DB_PASS:-test}
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASS:-secret}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - default

  postgres:
    container_name: study-kotlin-postgres-container
    hostname: study-kotlin-postgres-server
    image: study-kotlin/postgres:dev
    build:
      context: .
      dockerfile: ./infra/docker/postgres/Dockerfile
      cache_from:
        - study-kotlin/postgres:cache
    restart: always
    ports:
      - '15434:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME:-kotlin2}
      - POSTGRES_USER=${POSTGRES_DB_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS:-test}
      - TZ=Asia/Tokyo
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
      - ./infra/docker/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  localstack:
    container_name: study-kotlin-localstack-container
    hostname: study-kotlin-localstack-server
    image: study-kotlin/localstack:dev
    build:
      context: .
      dockerfile: ./infra/docker/localstack/Dockerfile
      cache_from:
        - study-kotlin/localstack:cache
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    ports:
      - '14564:4566'
    volumes:
      - localstack-data-volume:/var/lib/localstack
      - ./infra/docker/localstack/init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - localhost.localstack.cloud

networks:
  default:
    name: study-kotlin

volumes:
  mysql-data-volume:
    name: study-kotlin-mysql-data
    driver: local
  postgres-data-volume:
    name: study-kotlin-postgres-data
    driver: local
  localstack-data-volume:
    name: study-kotlin-localstack-data
    driver: local
