name: 'kotlin-kcl-sample'

services:
  consumer-app:
    container_name: kotlin-kcl-sample-consumer-app-container
    hostname: kotlin-kcl-sample-consumer-app-server
    image: kotlin-kcl-sample/consumer-app:dev
    build:
      context: .
      dockerfile: ./infra/docker/consumer-app/Dockerfile
      cache_from:
        - kotlin-kcl-sample/consumer-app:cache
      target: dev
    depends_on:
      - postgres
    env_file:
      - app-local.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: sync
          path: ./consumer-app
          target: /app
        - action: rebuild
          path: ./consumer-app/build.gradle.kts
    command: ["sh", "start.sh"]

  postgres:
    container_name: kotlin-kcl-sample-postgres-container
    hostname: kotlin-kcl-sample-postgres-server
    image: kotlin-kcl-sample/postgres:dev
    build:
      context: .
      dockerfile: ./infra/docker/postgres/Dockerfile
      cache_from:
        - kotlin-kcl-sample/postgres:cache
    restart: always
    ports:
      - '15434:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME:-kotlin_kcl_sample}
      - POSTGRES_USER=${POSTGRES_DB_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS:-test}
      - TZ=Asia/Tokyo
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
      - ./infra/docker/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -D kotlin_kcl_sample"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  localstack:
    container_name: kotlin-kcl-sample-localstack-container
    hostname: kotlin-kcl-sample-localstack-server
    image: kotlin-kcl-sample/localstack:dev
    build:
      context: .
      dockerfile: ./infra/docker/localstack/Dockerfile
      cache_from:
        - kotlin-kcl-sample/localstack:cache
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DISABLE_CORS_CHECKS=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
    ports:
      - '14564:4566'
    volumes:
      - localstack-data-volume:/var/lib/localstack
      - ./infra/docker/localstack/init/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - localhost.localstack.cloud

networks:
  default:
    name: kotlin-kcl-sample

volumes:
  postgres-data-volume:
    name: kotlin-kcl-sample-postgres-data
    driver: local
  localstack-data-volume:
    name: kotlin-kcl-sample-localstack-data
    driver: local
