spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_DATABASE_USER}
    password: ${POSTGRES_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Tokyo
        format_sql: true
        globally_quoted_identifiers: true #予約済キーワードをエスケープするための構成
        globally_quoted_identifiers_skip_column_definitions: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
postgres:
  url: ${POSTGRES_DATABASE_URL}
  username: ${POSTGRES_DATABASE_USER}
  password: ${POSTGRES_DATABASE_PASSWORD}
aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_ACCESS_SECRET_KEY}
  region: ${AWS_REGION}
kinesis:
  endpoint: ${AWS_KINESIS_DEV_ENDPOINT}
  streamName: ${AWS_KINESIS_STREAM_NAME}
dynamodb:
  endpoint: ${AWS_DYNAMO_DB_DEV_ENDPOINT}
cloudwatch:
  endpoint: ${AWS_CLOUD_WATCH_DEV_ENDPOINT}
