spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://study-kotlin-postgres-container:5432/study_kotlin}
    username: ${POSTGRES_DATABASE_USER:test}
    password: ${POSTGRES_DATABASE_PASSWORD:test}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Tokyo
        format_sql: true
        globally_quoted_identifiers: true #予約済キーワードをエスケープするための構成
        globally_quoted_identifiers_skip_column_definitions: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
#TODO: .envの環境変数が読み込まれるようにする
postgres:
  url: ${POSTGRES_DATABASE_URL:jdbc:postgresql://study-kotlin-postgres-container:5432/study_kotlin}
  username: ${POSTGRES_DATABASE_USER:test}
  password: ${POSTGRES_DATABASE_PASSWORD:test}
aws:
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_ACCESS_SECRET_KEY:test}
  region: ${AWS_REGION:ap-northeast-1}
kinesis:
  endpoint: ${AWS_KINESIS_DEV_ENDPOINT:http://study-kotlin-localstack-container:4566}
  region: ${AWS_KINESIS_REGION:ap-northeast-1}
  streamName: ${AWS_KINESIS_STREAM_NAME:study-kotlin-stream}
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_ACCESS_SECRET_KEY:test}
dynamodb:
  endpoint: ${AWS_DYNAMO_DB_DEV_ENDPOINT:http://study-kotlin-localstack-container:4566}
  region: ${AWS_DYNAMO_DB_REGION:ap-northeast-1}
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_ACCESS_SECRET_KEY:test}
cloudwatch:
  endpoint: ${AWS_CLOUD_WATCH_DEV_ENDPOINT:http://study-kotlin-localstack-container:4566}
  region: ${AWS_CLOUD_WATCH_REGION:ap-northeast-1}
  accessKey: ${AWS_ACCESS_KEY:test}
  secretKey: ${AWS_ACCESS_SECRET_KEY:test}
